import{FilesetResolver,HandLandmarker}from'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm';
import{HandProcessor}from'./core.js';
import{ExperimentRenderer}from'./experiments.js';
const $=s=>document.querySelector(s),app=$('#app'),frameEl=$('#frame'),video=$('#video'),start=$('#start'),startBtn=$('#startBtn'),status=$('#status'),error=$('#error');
const settings={smoothing:.55,pinchOn:.72,pinchOff:.55,holdMs:80,rate:22};
try{Object.assign(settings,JSON.parse(localStorage.getItem('handkit-settings')||'null')||{})}catch{}
let tracker,running=false,busy=false,mirror=true,fit='cover',facing='user',stream,lastVideoTime=-1,lastRun=0,currentFrame={timestamp:0,hands:[],events:[]},delegate='GPU',inference=0,vFrames=0,tFrames=0,apiFrames=0,lastMetrics=performance.now(),labelMode='events',lastLabelAt=0,recording=false,recordStarted=0,recorded=[];
const subscribers=new Set,eventSubscribers=new Map,eventHistory=[];
const renderer=new ExperimentRenderer($('#overlay'),frameEl);renderer.draw();
function mapPoint(p){const r=frameEl.getBoundingClientRect(),sw=video.videoWidth||1,sh=video.videoHeight||1,s=fit==='cover'?Math.max(r.width/sw,r.height/sh):Math.min(r.width/sw,r.height/sh),rw=sw*s,rh=sh*s,ox=(r.width-rw)/2,oy=(r.height-rh)/2,x=mirror?1-p.x:p.x;return{x:ox+x*rw,y:oy+p.y*rh,z:p.z}}
function fail(message){error.textContent=message;error.classList.add('show');status.textContent='Error';setTimeout(()=>error.classList.remove('show'),8000)}
function showLabel(text){if(labelMode==='off')return;const n=$('#gestureName');n.textContent=text;n.classList.add('show');lastLabelAt=performance.now();setTimeout(()=>{if(performance.now()-lastLabelAt>650)n.classList.remove('show')},700)}
function renderEvents(){const el=$('#eventLog');el.innerHTML=eventHistory.length?eventHistory.slice(0,12).map(e=>`<div>${e.hand?.id||'system'} · ${e.type}</div>`).join(''):'<div>Waiting for tracking…</div>'}
function emit(event){eventHistory.unshift(event);if(eventHistory.length>24)eventHistory.length=24;eventSubscribers.get(event.type)?.forEach(fn=>fn(event));eventSubscribers.get('*')?.forEach(fn=>fn(event));renderEvents();if(event.type.endsWith('start'))showLabel(event.type.replace('start',''));if(event.type==='pinchstart')renderer.burst(event.hand?.screen?.indexTip)}
const processor=new HandProcessor({mapPoint,getSettings:()=>settings,onEvent:emit});
function updateHud(){const count=currentFrame.hands.length;$('#handsPill').textContent=count?`${count} hand${count>1?'s':''}`:'Show your hands';for(const name of['pinch','open','fist','point','victory']){const el=$('#'+name+'Pill'),active=currentFrame.hands.some(h=>h.gestures.states[name]),max=Math.max(0,...currentFrame.hands.map(h=>h.gestures[name]||0));el.textContent=`${name[0].toUpperCase()+name.slice(1)} ${Math.round(max*100)}%`;el.classList.toggle('on',active)}$('#handM').textContent=count;if(labelMode==='always'){const all=currentFrame.hands.flatMap(h=>['pinch','open','fist','point','victory'].map(k=>({k,v:h.gestures[k]}))).sort((a,b)=>b.v-a.v),n=$('#gestureName');if(all[0]?.v>.65){n.textContent=all[0].k;n.classList.add('show')}else n.classList.remove('show')}}
async function initTracker(){status.textContent='Loading hand model…';const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'),make=d=>HandLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:d},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5});try{tracker=await make('GPU')}catch{delegate='CPU';tracker=await make('CPU')}$('#delegateM').textContent=delegate;status.textContent='Tracking ready'}
async function openCamera(){stream?.getTracks().forEach(t=>t.stop());status.textContent='Opening camera…';stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1920,min:1280},height:{ideal:1080,min:720},frameRate:{ideal:30,max:60}}});video.srcObject=stream;await video.play();const s=stream.getVideoTracks()[0].getSettings();$('#cameraM').textContent=`${s.width||video.videoWidth}×${s.height||video.videoHeight} @ ${Math.round(s.frameRate||0)}`;status.textContent='Camera active'}
async function startCamera(){startBtn.disabled=true;startBtn.textContent='Starting…';try{await openCamera();start.classList.add('hide');$('#experimentBar').classList.add('show');$('#gestureHud').classList.add('show');running=true;initTracker().catch(e=>fail('Model failed: '+e));loop()}catch(e){startBtn.disabled=false;startBtn.textContent='Try again';fail(e.message||String(e))}}
function loop(now=performance.now()){if(!running)return;vFrames++;if(tracker&&!busy&&video.currentTime!==lastVideoTime&&now-lastRun>1000/settings.rate){busy=true;lastVideoTime=video.currentTime;lastRun=now;const t=performance.now();try{currentFrame=processor.process(tracker.detectForVideo(video,now),now);inference=performance.now()-t;tFrames++;renderer.setFrame(currentFrame);updateHud();subscribers.forEach(fn=>fn(currentFrame));apiFrames++;if(recording){recorded.push({t:now-recordStarted,hands:currentFrame.hands.map(h=>({id:h.id,landmarks:h.landmarks,gestures:h.gestures})),twoHand:currentFrame.twoHand});if(now-recordStarted>30000)stopRecording()}}catch(e){fail('Tracking failed: '+e)}busy=false}requestAnimationFrame(loop)}
function startRecording(){recording=true;recorded=[];recordStarted=performance.now();$('#recordBtn').textContent='Stop';$('#recordBtn').classList.add('rec');$('#recDot').classList.add('show')}
async function stopRecording(){if(!recording)return;recording=false;$('#recordBtn').textContent='Record';$('#recordBtn').classList.remove('rec');$('#recDot').classList.remove('show');const file=new File([JSON.stringify({version:'0.2',createdAt:new Date().toISOString(),settings:{...settings},frames:recorded})],`handkit-${Date.now()}.json`,{type:'application/json'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'HandKit recording'});else{const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click()}}catch(e){if(e.name!=='AbortError')fail('Could not save recording: '+e.message)}}
function setExperiment(name){renderer.setExperiment(name);document.querySelectorAll('[data-exp]').forEach(b=>b.classList.toggle('on',b.dataset.exp===name));$('#experimentM').textContent=({lab:'Gesture Lab',trails:'Trails',portal:'Portal',spotlight:'Spotlight',echo:'Echo'})[name]||name}
setInterval(()=>{const now=performance.now(),dt=now-lastMetrics;$('#videoM').textContent=Math.round(vFrames*1000/dt)+' FPS';$('#trackM').textContent=Math.round(tFrames*1000/dt)+' FPS';$('#inferM').textContent=inference?inference.toFixed(1)+' ms':'–';$('#apiM').textContent=apiFrames;vFrames=tFrames=apiFrames=0;lastMetrics=now;if(recording){const s=Math.floor((now-recordStarted)/1000);$('#recTime').textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}},1000);
window.HandKit={version:'0.2.0',getFrame:()=>currentFrame,subscribe(fn){subscribers.add(fn);return()=>subscribers.delete(fn)},on(type,fn){if(!eventSubscribers.has(type))eventSubscribers.set(type,new Set);eventSubscribers.get(type).add(fn);return()=>eventSubscribers.get(type)?.delete(fn)},setExperiment,getSettings:()=>({...settings})};
startBtn.onclick=startCamera;$('#cameraBtn').onclick=async e=>{facing=facing==='user'?'environment':'user';e.currentTarget.textContent=facing==='user'?'Front':'Rear';try{await openCamera()}catch(err){fail(err.message)}};$('#edge').onclick=e=>{app.classList.toggle('edge');e.currentTarget.textContent=app.classList.contains('edge')?'Edge':'Frame'};$('#fit').onclick=e=>{fit=fit==='cover'?'contain':'cover';video.classList.toggle('contain',fit==='contain');e.currentTarget.textContent=fit[0].toUpperCase()+fit.slice(1)};$('#mirror').onclick=e=>{mirror=!mirror;video.style.transform=mirror?'scaleX(-1)':'none';e.currentTarget.classList.toggle('on',mirror)};$('#skeleton').onclick=e=>{renderer.setSkeleton(!renderer.showSkeleton);e.currentTarget.classList.toggle('on',renderer.showSkeleton)};$('#recordBtn').onclick=()=>recording?stopRecording():startRecording();$('#debugBtn').onclick=e=>{$('#debug').classList.toggle('show');$('#settings').classList.remove('show');e.currentTarget.classList.toggle('on');$('#settingsBtn').classList.remove('on')};$('#settingsBtn').onclick=e=>{$('#settings').classList.toggle('show');$('#debug').classList.remove('show');e.currentTarget.classList.toggle('on');$('#debugBtn').classList.remove('on')};document.querySelectorAll('[data-exp]').forEach(b=>b.onclick=()=>setExperiment(b.dataset.exp));
function bindRange(id,key,display,format){const el=$(id),out=$(display);el.oninput=()=>{settings[key]=key==='smoothing'||key==='pinchOn'?+el.value/100:+el.value;if(key==='pinchOn')settings.pinchOff=Math.max(.3,settings.pinchOn-.17);out.textContent=format(settings[key]);localStorage.setItem('handkit-settings',JSON.stringify(settings))}}
bindRange('#smoothRange','smoothing','#smoothValue',v=>Math.round(v*100)+'%');bindRange('#pinchRange','pinchOn','#pinchValue',v=>Math.round(v*100)+'%');bindRange('#holdRange','holdMs','#holdValue',v=>v+' ms');bindRange('#rateRange','rate','#rateValue',v=>v+' FPS');$('#labelSelect').onchange=e=>{labelMode=e.target.value;if(labelMode==='off')$('#gestureName').classList.remove('show')};$('#resetSettings').onclick=()=>{localStorage.removeItem('handkit-settings');location.reload()};
$('#smoothRange').value=settings.smoothing*100;$('#smoothValue').textContent=Math.round(settings.smoothing*100)+'%';$('#pinchRange').value=settings.pinchOn*100;$('#pinchValue').textContent=Math.round(settings.pinchOn*100)+'%';$('#holdRange').value=settings.holdMs;$('#holdValue').textContent=settings.holdMs+' ms';$('#rateRange').value=settings.rate;$('#rateValue').textContent=settings.rate+' FPS';
