export const connections=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[5,9],[9,10],[10,11],[11,12],[9,13],[13,14],[14,15],[15,16],[13,17],[17,18],[18,19],[19,20],[0,17]];
export const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export const lerp=(a,b,t)=>a+(b-a)*t;
export const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y,(a.z-b.z)*.35);
export const avg=pts=>({x:pts.reduce((s,p)=>s+p.x,0)/pts.length,y:pts.reduce((s,p)=>s+p.y,0)/pts.length,z:pts.reduce((s,p)=>s+p.z,0)/pts.length});
class GestureGate{constructor(on,off,hold=80,release=80){Object.assign(this,{on,off,hold,release,active:false,candidateAt:0,releaseAt:0})}update(value,now){let event=null;if(!this.active){if(value>=this.on){if(!this.candidateAt)this.candidateAt=now;if(now-this.candidateAt>=this.hold){this.active=true;this.candidateAt=0;event='start'}}else this.candidateAt=0}else if(value<=this.off){if(!this.releaseAt)this.releaseAt=now;if(now-this.releaseAt>=this.release){this.active=false;this.releaseAt=0;event='end'}}else this.releaseAt=0;return{active:this.active,event}}}
export class HandProcessor{
 constructor({mapPoint,getSettings,onEvent}){this.mapPoint=mapPoint;this.getSettings=getSettings;this.onEvent=onEvent;this.smoothCache=new Map;this.machines=new Map}
 extension(l,tip,pip,mcp){const a=dist(l[tip],l[0]),b=dist(l[pip],l[0]),c=dist(l[mcp],l[0]);return clamp((a-b)/(Math.max(b-c,.0001)*1.4)+.35)}
 values(l){const palm=Math.max(dist(l[5],l[17]),.02),pd=dist(l[4],l[8])/palm,pinch=clamp(1-(pd-.16)/.65),index=this.extension(l,8,6,5),middle=this.extension(l,12,10,9),ring=this.extension(l,16,14,13),pinky=this.extension(l,20,18,17),open=clamp((index+middle+ring+pinky)/3.7),fist=clamp(1-open),point=clamp(index*((1-middle)+(1-ring)+(1-pinky))/3),victory=clamp(((index+middle)/2)*((1-ring)+(1-pinky))/2),grab=clamp(fist*.75+pinch*.25);return{pinch,open,fist,point,victory,grab,fingers:{index,middle,ring,pinky}}}
 smooth(key,lm){const settings=this.getSettings(),prev=this.smoothCache.get(key),follow=1-settings.smoothing*.82;if(!prev){const first=lm.map(p=>({...p}));this.smoothCache.set(key,first);return first}const out=lm.map((p,i)=>({x:lerp(prev[i].x,p.x,follow),y:lerp(prev[i].y,p.y,follow),z:lerp(prev[i].z,p.z,Math.min(1,follow*1.25))}));this.smoothCache.set(key,out);return out}
 machine(key){const s=this.getSettings();if(!this.machines.has(key))this.machines.set(key,{pinch:new GestureGate(s.pinchOn,s.pinchOff,s.holdMs,70),open:new GestureGate(.78,.58,s.holdMs,100),fist:new GestureGate(.78,.56,s.holdMs,100),point:new GestureGate(.72,.5,s.holdMs,100),victory:new GestureGate(.7,.48,s.holdMs,100)});const m=this.machines.get(key);m.pinch.on=s.pinchOn;m.pinch.off=s.pinchOff;Object.values(m).forEach(g=>g.hold=s.holdMs);return m}
 process(result,now){const frame={timestamp:now,hands:[],events:[],twoHand:null,provider:'mediapipe'};for(let i=0;i<result.landmarks.length;i++){const handed=result.handedness?.[i]?.[0]?.categoryName||`Hand ${i+1}`,l=this.smooth(handed,result.landmarks[i]),values=this.values(l),machine=this.machine(handed),screenLandmarks=l.map(this.mapPoint),palm=avg([l[0],l[5],l[9],l[13],l[17]]),hand={id:handed,handedness:handed,landmarks:l,screenLandmarks,palm,screen:{palm:this.mapPoint(palm),indexTip:screenLandmarks[8],thumbTip:screenLandmarks[4]},gestures:{...values,states:{}},confidence:result.handedness?.[i]?.[0]?.score||1};for(const name of['pinch','open','fist','point','victory']){const state=machine[name].update(values[name],now);hand.gestures.states[name]=state.active;if(state.event){const event={type:name+state.event,timestamp:now,hand,value:values[name]};frame.events.push(event);this.onEvent(event)}}frame.hands.push(hand)}if(frame.hands.length===2){const a=frame.hands[0].screen.palm,b=frame.hands[1].screen.palm,separation=Math.hypot(a.x-b.x,a.y-b.y);frame.twoHand={center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2},separation}}return frame}
}
